name: Generate Stats Images

on:
  push:
    branches:
      - master
  schedule:
    - cron: "35 0 * * *"
  workflow_dispatch:

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Zig
        uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2 tag
        with:
          version: 0.16.0

      - name: Build
        run: |
          zig build

      - name: Generate images
        run: |
          ./zig-out/bin/github-stats
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EXCLUDE_REPOS: ${{ secrets.EXCLUDE_REPOS }}
          EXCLUDE_LANGS: ${{ secrets.EXCLUDE_LANGS }}
          EXCLUDE_FORKED_REPOS: "true"
          EXCLUDE_PRIVATE: "false"
          SILENT: "true"
          # TODO: Remove this when they get their API working again
          # https://github.com/orgs/community/discussions/192970
          MAX_RETRIES: 5

      - name: Move generated svg files to the correct location
        run: |
          mv *.svg generated/

      # Commit all changed files to the repository
      - name: Commit to the repo
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          # Force the build to succeed, even if no files were changed
          git commit -m 'Update generated files' || true
          git push
